apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: game1
  name: game1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: game1
    spec:
      containers:
      - image: tictactoe-game-web
        name: game1
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: game1